# Generated by Django 4.2.8 on 2023-12-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
