# Generated by Django 5.0 on 2023-12-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['quiz__id', 'order']},
        ),
    ]
