# Generated by Django 5.0 on 2024-01-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
    ]
