# Generated by Django 5.0 on 2024-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_useranswer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_attempts',
            field=models.IntegerField(default=2, verbose_name='Počet pokusů'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
