# Generated by Django 5.0 on 2023-12-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_useranswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_order',
            field=models.IntegerField(default=0),
        ),
    ]
