# Generated by Django 5.0 on 2023-12-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_option_option_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
