# Generated by Django 5.0 on 2024-01-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_useranswer_missing_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='missing_answer',
            new_name='missing_answers',
        ),
    ]
