# Generated by Django 5.0 on 2023-12-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_option_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ai_api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ai_model',
            field=models.CharField(choices=[('gpt-4', 'gpt-4'), ('gpt-4t', 'gpt-4 turbo'), ('gpt-3.5t', 'gpt-3.5-turbo')], default='gpt-3.5t', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='ai_prompt_prefix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='example_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='ai_prompt_prefix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
