# Generated by Django 5.0 on 2023-12-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_course_ai_api_key_course_ai_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='ai_prompt_prefix',
            new_name='ai_prompt_quiz_text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ai_prompt_prefix',
        ),
        migrations.AddField(
            model_name='course',
            name='ai_prompt_format',
            field=models.TextField(blank=True, null=True),
        ),
    ]
