# Generated by Django 5.0 on 2023-12-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_chatgptlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgptlog',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='chatgptlog',
            name='request',
        ),
        migrations.AddField(
            model_name='chatgptlog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatgptlog',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
