# Generated by Django 5.0 on 2023-12-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_chatgptlog_prompt_remove_chatgptlog_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_feedback_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('gpt-4', 'gpt-4')], default='gpt-4', max_length=20),
        ),
    ]
